spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_MULTIPLE_DATABASES:creditrama_client}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:docker}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: profile
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - ${KAFKA_BROKER:localhost}

security:
  oauth2:
    resource:
      access-token-uri: http://${AUTHORIZATION_HOST:localhost}:9191/oauth/token
      token-info-uri: http://${AUTHORIZATION_HOST:localhost}:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
service.bankaccount: ${SERVICE_BANKACCOUNT:http://localhost:8083/}
