spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/creditrama?createDatabaseIfNotExist=true
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: profile
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost
            - kafka

security:
  oauth2:
    resource:
      token-info-uri: http://login:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

